#!/usr/local/bin/php -q
<?php
include('/usr/local/apache/servers/statmvs.mariupol.net/include/connect.inc');
include('/usr/local/apache/servers/statmvs.mariupol.net/include/radiusdb.inc');
$query="select radacct.*,dogovor.* from radacct,dogovor where dogovor.domen=radacct.username and radacct.AcctStopTime like '0000-00-00 00:00:00' order by radacct.username";
$res=mysql("mvs",$query);
$num=mysql_num_rows($res);
echo mysql_error();
for ($i=0;$i < $num;$i++) {
  $user=mysql_result($res,$i,"radacct.username");
  $tty=mysql_result($res,$i,"NASPortId");
  $sessionsid=mysql_result($res,$i,"AcctUniqueId");
  $query="select min(AcctStartTime) from radacct where AcctUniqueId like '$sessionsid'";
//  echo $query;
  $res1=mysql("mvs",$query);
  $date=mysql_result($res1,0,"min(AcctStartTime)");
  $speed=get_speed_radgroupreply($user);
  $query="select * from radreply where username like '$user' and Attribute like 'Cisco-AVPair' and value like '%rate_limit%'";
  $res2=mysql("mvs",$query);
  $nums=mysql_num_rows($res2);
  if ($nums > 0 ) {
    $speed=get_speed_radreply($user);
  }
  $speedin=$speed[0]/1024;
  $speedout=$speed[1]/1024;
  $speeds=$speedin."/".$speedout;
//  $date=mysql_result($res,$i,"radacct.AcctStartTime");
//  $access=mysql_result($res,$i,"access");
  $address=mysql_result($res,$i,"dogovor.address");
  $mvsip=mysql_result($res,$i,"radacct.TunnelClientEndpoint");
//  $interface=mysql_result($res,$i,"interface");
  echo sprintf("%15s %4s %1s %15s %1s %9s %15s %15s\n",$user,$tty,$interface,$date,$access,$speeds,$mvsip,$address);
}
echo "$num users\n";
?>
