#!/usr/local/bin/php -q
<?php

include('/usr/local/apache/servers/statmvs.mariupol.net/include/function.inc');
include("/usr/local/apache/servers/statmvs.mariupol.net/include/connect.inc");
loadallprice();
loadchap();
?>
